- name: Install K3s on worker node and join cluster
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars[groups['k3s_master'][0]].inventory_hostname }}:6443 K3S_TOKEN={{ hostvars[groups['k3s_master'][0]].master_token }} sh -
  args:
    creates: /usr/local/bin/k3s
