ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/cloud_vm
ansible_python_interpreter: /usr/bin/python3.12
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
