
- name: Install K3s on master node
  shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s
  register: k3s_install

- name: Retrieve the K3s token for joining worker nodes
  command: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token

- name: Set token fact for other hosts
  set_fact:
    master_token: "{{ k3s_token.stdout }}"
  
- name: Append advertise-address and tls-san to k3s service file
  blockinfile:
    path: /etc/systemd/system/k3s.service
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: EOF
    block: |
      '–advertise-address={{ hostvars[groups['k3s_master'][0]].inventory_hostname }}' \
      '-tls-san={{ hostvars[groups['k3s_master'][0]].inventory_hostname }}' \
  

- name: Delete k3s-serving secret and move dynamic-cert.json
  shell: |
    k3s kubectl -n kube-system delete secrets/k3s-serving
    mv /var/lib/rancher/k3s/server/tls/dynamic-cert.json /tmp/dynamic-cert.json
  become: yes
  notify: Reload systemd daemon

- name: Copy k3s kubeconfig file from master node to local system
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /mnt/c/Users/Jilvin/.kube/
    flat: yes

- name: Modify the copied kubeconfig file on the local system
  lineinfile:
    path: /mnt/c/Users/Jilvin/.kube/k3s.yaml
    regexp: '^\s*server: https://.*'
    line: '    server: https://{{ hostvars[groups["k3s_master"][0]].inventory_hostname }}:6443'
  delegate_to: localhost
  become: no



        

